stages:
  - test
  - build
  - deploy

unit tests:
  stage: test
  tags: [gitlab-org-docker]
  image: python:3.7
  script:
    - pip install --no-cache-dir -r requirements.txt
    - python showpipeline_tests.py

android:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 20
    - echo "build 1"

ios:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 24
    - echo "build 2"

staging:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 10
    - echo "deploy"