stages:
  - docker
  - test
  - deploy

variables:
  DOCKER_IMAGE_VERSION: 1

build docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_VERSION
  only:
    changes:
      - Dockerfile
      - requirments.txt

unit tests:
  stage: test
  tags: [gitlab-org-docker]
  image: $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_VERSION
  script:
    - coverage run --source='.' showpipeline_tests.py
    - coverage xml
    - coverage html
  artifacts:
    paths:
      - htmlcov/
    reports:
      cobertura: coverage.xml
  coverage: '/^TOTAL.*\s+(\d+\%)$/'

pages:
  stage: deploy
  dependencies:
    - unit tests
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

notify merge request:
  stage: deploy
  tags: [ gitlab-org-docker ]
  image: $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_VERSION
  script:
    - echo $CI_PIPELINE_IID
    - echo $CI_PIPELINE_ID
    - python gitlab_helper.py
