stages:
  - test
  - build
  - deploy

unit tests:
  stage: test
  tags: [gitlab-org-docker]
  image: python:3.7
  script:
    - pip install --no-cache-dir -r requirements.txt
    - python showpipeline_tests.py

stub build 1:
  stage: build
  allow_failure: true
  variables:
    GIT_STRATEGY: none
  script:
    - exit 1
    - echo "build 1"

stub build 2:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - echo "build 2"

stub deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - exit 1
    - echo "deploy"