#!/usr/bin/env python

import sys

from pipeline_mermaid.gitlab_helper import GitlabHelper

if __name__ == "__main__":
    gl = GitlabHelper()
    result = eval("GitlabHelper." + sys.argv[1])(gl, *sys.argv[2:])